# Generated by Django 3.2.2 on 2021-06-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reviews', '0002_ticket_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='headline',
            new_name='title',
        ),
    ]
