# Generated by Django 3.2.2 on 2021-06-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reviews', '0003_auto_20210601_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/upload/'),
        ),
    ]
