# Generated by Django 3.2.2 on 2021-06-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reviews', '0005_alter_review_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='content',
            new_name='description',
        ),
    ]
